### ISSUE TITLE
I can not plot imported length data

### ISSUE THREAD

**Issue by IldarSafaraliev** [AdrianHordyk/LBSPR#8] opened 2020-05-23 22:27 UTC
Hi Adrian Hordyk.
I study a manual for LBSPR package. I ran into one problem - can not plot the imported length data.
I run all codes in the  manual :
MyPars <- new("LB_pars")
MyPars@Species <- "MySpecies"
MyPars@Linf <- 100 
MyPars@L50 <- 66 
MyPars@L95 <- 70
MyPars@MK <- 1.5 
MyPars@L_units <- "mm"
Len1 <- new("LB_lengths", LB_pars=MyPars, file=paste0(datdir, "/LFreq_MultiYr.csv"), 
            dataType="freq")
Len2 <- new("LB_lengths", LB_pars=MyPars, file=paste0(datdir, "/LFreq_MultiYrHead.csv"), 
            dataType="freq", header=TRUE)
Len3 <- new("LB_lengths", LB_pars=MyPars, file=paste0(datdir, "/LRaw_MultiYr.csv"), 
            dataType="raw")
PlotSize (Len1) an so on.
But i get  wrong plots like in an attached file.
Could you explaine what i do wrong?
![Rplot](https://user-images.githubusercontent.com/65832936/82741707-23bc7600-9d66-11ea-84b6-436c57c2967c.jpeg)

**Comment by AdrianHordyk** [comment] 2020-05-25 16:48
This problem is caused by the latest version of the `ggplot2` package. I believe it will be fixed soon. In the meantime, the issue is fixed in the development version of `LBSPR` package from Github: 

```
install.packages('devtools')
devtools::install_github("adrianhordyk/LBSPR")
```

**Closed as completed** 2020-05-25 16:48 UTC
